version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7.2.17-stretch
    steps:
    - run: sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - checkout
    - run: composer validate --strict
    - run: composer install --no-interaction --no-suggest
    - run: vendor/bin/parallel-lint bootstrap.php src/
    - run: vendor/bin/phpcs --standard=PSR12NeutronRuleset --exclude=PEAR.Commenting.ClassComment,PEAR.Commenting.FileComment,Generic.Files.LineLength bootstrap.php src/
    - run: vendor/bin/phpstan analyze
workflows:
  version: 2
  workflow:
    jobs:
    - test:
        filters:
          branches:
            only:
            - master
